import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";
import prettierConfig from "eslint-config-prettier";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    ignores: [
      ".next/**",
      ".next-e2e/**",
      ".next-analyze/**",
      "out/**",
      "build/**",
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
      "next-env.d.ts",
      // Generated by `npm run api:types` from the API's OpenAPI spec.
      "utils/interfaces/generated/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // lucide-react exports every icon three ways — `Home`, `HomeIcon` and
      // `LucideHome` — and the codebase had drifted across all three, with 31
      // files mixing conventions inside a single import block. The Lucide*
      // alias won on volume (455 of 696) and it keeps icons distinguishable in
      // the import lists here that run to thirty-plus symbols.
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "ImportDeclaration[source.value='lucide-react'] > ImportSpecifier[imported.name!=/^Lucide/]",
          message:
            "Import lucide-react icons under their Lucide* alias (LucideHome, not Home or HomeIcon).",
        },
      ],
    },
  },
  // Must stay last: turns off the stylistic rules Prettier owns.
  prettierConfig,
];

export default eslintConfig;
