export type TLocations = 
  | 'Banteay Meanchey'
  | 'Battambang'
  | 'Kampong Cham'
  | 'Kampong Chhnang'
  | 'Kampong Speu'
  | 'Kampong Thom'
  | 'Kampot'
  | 'Kandal'
  | 'Kep'
  | 'Koh Kong'
  | 'Kratie'
  | 'Mondulkiri'
  | 'Oddar Meanchey'
  | 'Pailin'
  | 'Phnom Penh' // Capital city with provincial status
  | 'Preah Sihanouk'
  | 'Preah Vihear'
  | 'Prey Veng'
  | 'Pursat'
  | 'Ratanakiri'
  | 'Siem Reap'
  | 'Stung Treng'
  | 'Svay Rieng'
  | 'Takeo'
  | 'Tbong Khmum';