"use client";

import Link from "next/link";
import {
  LucideArrowLeft,
  LucideCalendar,
  LucideDatabase,
  LucideLock,
  LucideMail,
  LucideRefreshCw,
  LucideServer,
  LucideShare2,
  LucideShieldCheck,
  LucideUser,
  LucideUserCheck,
} from "lucide-react";
import { TypographyH1 } from "@/components/utils/typography/typography-h1";
import { TypographyH2 } from "@/components/utils/typography/typography-h2";
import { TypographyP } from "@/components/utils/typography/typography-p";
import { TypographySmall } from "@/components/utils/typography/typography-small";
import { useLanguageStore } from "@/stores/languages/language-store";
import { EditorialIllustration } from "@/components/utils/data-display/editorial-illustration";

/* -------------------------- Sub Components -------------------------- */
function Section({
  id,
  icon,
  title,
  children,
}: {
  id: string;
  icon: React.ReactNode;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section id={id} className="flex flex-col gap-4 scroll-mt-8">
      <div className="flex items-center gap-3">
        <div className="flex items-center justify-center size-9 rounded-xl bg-primary/10 border border-primary/20 shrink-0">
          <span className="text-primary [&>svg]:size-4">{icon}</span>
        </div>
        <TypographyH2 className="text-lg font-bold tracking-tight">
          {title}
        </TypographyH2>
      </div>
      <div className="flex flex-col gap-3 text-sm text-muted-foreground leading-relaxed pl-0">
        {children}
      </div>
    </section>
  );
}

function Bullet({ children }: { children: React.ReactNode }) {
  return (
    <li className="flex items-start gap-2">
      <span className="mt-1.5 size-1.5 rounded-full bg-primary/60 shrink-0" />
      <span>{children}</span>
    </li>
  );
}

/* -------------------------- Content & Data -------------------------- */
const content = {
  en: {
    back: "Back",
    pageTitle: "Privacy Policy",
    lastUpdated: "Last updated: March 24, 2026",
    tocHeading: "Contents",
    intro:
      "At Apsara Talent, we are committed to protecting your personal information. This Privacy Policy explains what data we collect, why we collect it, and how we use and safeguard it when you use our talent-matching platform.",
    introCompany: "Apsara Talent",

    toc: [
      { id: "information-we-collect", label: "Information We Collect" },
      { id: "how-we-use", label: "How We Use Your Information" },
      { id: "how-we-share", label: "How We Share Your Information" },
      { id: "third-party", label: "Third-Party Services" },
      { id: "data-retention", label: "Data Retention" },
      { id: "security", label: "Security" },
      { id: "your-rights", label: "Your Rights" },
      { id: "cookies", label: "Cookies & Storage" },
      { id: "children", label: "Children's Privacy" },
      { id: "changes", label: "Changes to This Policy" },
      { id: "contact", label: "Contact Us" },
    ],

    s1: {
      title: "Information We Collect",
      intro:
        "We collect information you provide directly, information generated by your use of the platform, and information from third-party services you connect.",
      g1Title: "Account & Identity",
      g1: [
        "Full name, username, email address, and phone number",
        "Date of birth and gender (employees)",
        "Profile photo / avatar and, for companies, a cover image",
        "Password (stored as a secure hash — we never store it in plain text)",
        "Social login identifiers from Google, Facebook, LinkedIn, or GitHub when you choose those sign-in methods",
      ],
      g2Title: "Professional Information (Employees)",
      g2: [
        "Job title, years of experience, availability type, and career scopes",
        "Skills, work experience history, and educational background",
        "Resume and cover letter files you upload",
        "Social profile links (LinkedIn, GitHub, website, etc.)",
        "Location (province/city in Cambodia)",
      ],
      g3Title: "Company Information",
      g3: [
        "Company name, industry, size, founded year, and description",
        "Open job positions, available interview times, and company values/benefits",
        "Company location and contact details",
        "Company gallery images",
      ],
      g4Title: "Usage & Technical Data",
      g4: [
        "Pages visited, features used, and interactions within the platform",
        "Chat messages exchanged between users on the platform",
        "Favorites and matching actions (saves, likes, swipes)",
        "Push notification device token for delivering notifications",
        "Last login time, login method, and IP address",
        "Browser type, operating system, and device identifiers",
      ],
    },

    s2: {
      title: "How We Use Your Information",
      bullets: [
        "To create, verify, and maintain your account",
        "To power the talent-matching algorithm that surfaces relevant employees to companies and vice versa",
        "To enable real-time messaging between matched users",
        "To send push notifications about new matches, messages, and platform updates",
        "To generate AI-assisted resume drafts via the Resume Builder feature",
        "To personalise your feed and search results based on your profile and activity",
        "To detect fraud, enforce our Terms of Service, and maintain platform security",
        "To send transactional emails such as email verification, password reset, and account activity alerts",
        "To improve and develop new features through aggregated, anonymised analytics",
      ],
      note: "We do not sell your personal data to third parties or use it for unrelated advertising purposes.",
      notePrefix: "We do ",
      noteStrong: "not",
      noteSuffix:
        " sell your personal data to third parties or use it for unrelated advertising purposes.",
    },

    s3: {
      title: "How We Share Your Information",
      intro:
        "We do not sell or rent your personal data. We share information only in the following limited circumstances:",
      bullets: [
        {
          label: "With other users:",
          text: "Your public profile (name, job, skills, location, availability, description) is visible to the other user type — employees can be seen by companies and companies can be seen by employees — to facilitate matching and hiring.",
        },
        {
          label: "With service providers:",
          text: "We use trusted infrastructure providers (cloud hosting, database, email delivery) who process data on our behalf under strict data processing agreements.",
        },
        {
          label: "With social login providers:",
          text: "When you authenticate via Google, Facebook, LinkedIn, or GitHub, those services receive information according to their own privacy policies.",
        },
        {
          label: "For legal compliance:",
          text: "We may disclose data when required by Cambodian law, court orders, or to protect the rights and safety of our users.",
        },
        {
          label: "During business transfers:",
          text: "In the event of a merger, acquisition, or asset sale, your data may be transferred to the successor entity.",
        },
      ],
    },

    s4: {
      title: "Third-Party Services",
      intro:
        "Apsara Talent integrates the following third-party services. Each has its own privacy policy that governs their use of your data:",
      bullets: [
        {
          label: "Google Firebase:",
          text: "Used for push notification delivery (Firebase Cloud Messaging). Your device token is stored securely and used solely for notifications.",
        },
        {
          label: "Google OAuth / Google Sign-In:",
          text: "Optional authentication method. We receive your name, email, and profile picture from Google if you choose this option.",
        },
        {
          label: "Facebook Login:",
          text: "Optional authentication method governed by Meta's Data Policy.",
        },
        {
          label: "LinkedIn OAuth:",
          text: "Optional authentication for professional identity verification.",
        },
        {
          label: "GitHub OAuth:",
          text: "Optional authentication for technical professionals.",
        },
        {
          label: "Cloud Infrastructure (Railway):",
          text: "Our API and database are hosted on Railway. Data is processed in secure, industry-standard data centers.",
        },
      ],
    },

    s5: {
      title: "Data Retention",
      intro:
        "We retain your personal data for as long as your account is active or as needed to provide you with our services.",
      bullets: [
        "Account data is retained for the lifetime of your account.",
        "Chat messages are stored to provide a persistent messaging history. You may delete individual conversations.",
        "After account deletion, we retain certain data for up to 30 days before permanent erasure to allow for account recovery, except where longer retention is required by law.",
        "Anonymised, aggregated analytics data may be retained indefinitely as it cannot be linked to any individual.",
      ],
    },

    s6: {
      title: "Security",
      intro:
        "We implement industry-standard security measures to protect your data:",
      bullets: [
        "All data is transmitted over HTTPS/TLS encryption.",
        "Passwords are hashed using a strong one-way algorithm and are never stored in plain text.",
        "Optional Two-Factor Authentication (2FA) is available to add an extra layer of account security.",
        "Access to personal data is restricted to authorised personnel only.",
        "We perform regular security reviews of our infrastructure.",
      ],
      note: "While we take every reasonable precaution, no method of transmission over the internet is 100% secure. We encourage you to use a strong, unique password and enable 2FA.",
    },

    s7: {
      title: "Your Rights",
      intro:
        "You have the following rights with respect to your personal data:",
      bullets: [
        {
          label: "Access:",
          text: "Request a copy of the personal data we hold about you.",
        },
        {
          label: "Correction:",
          text: "Update or correct inaccurate information via your profile settings at any time.",
        },
        {
          label: "Deletion:",
          text: "Request deletion of your account and personal data.",
        },
        {
          label: "Portability:",
          text: "Request an export of your data in a structured, machine-readable format.",
        },
        {
          label: "Objection:",
          text: "Object to the processing of your data for specific purposes.",
        },
        {
          label: "Withdraw Consent:",
          text: "Withdraw consent for optional data processing at any time without affecting prior processing.",
        },
      ],
      note: "To exercise any of these rights, please contact us at",
      email: "privacy@apsaratalent.com",
      noteSuffix: ". We will respond within 30 days.",
    },

    s8: {
      title: "Cookies & Local Storage",
      intro: "We use browser cookies and local storage to:",
      bullets: [
        "Maintain your authentication session securely.",
        "Remember your theme preference (light / dark / system).",
        "Remember your language preference (English / ភាសាខ្មែរ).",
        "Store cached data locally to improve page load performance.",
      ],
      note: "We do not use third-party advertising cookies. You can clear cookies and local storage via your browser settings at any time, though this will sign you out of your account.",
    },

    s9: {
      title: "Children's Privacy",
      text: "Apsara Talent is intended for users who are 18 years of age or older. We do not knowingly collect personal information from individuals under 18. If we become aware that a user is under 18, we will promptly delete their account and associated data. If you believe a minor has registered an account, please contact us immediately.",
    },

    s10: {
      title: "Changes to This Policy",
      intro:
        "We may update this Privacy Policy from time to time to reflect changes in our practices, technology, legal requirements, or other factors. When we make material changes, we will:",
      bullets: [
        'Update the "Last updated" date at the top of this page.',
        "Send a notification to registered users via email or in-app notification.",
      ],
      note: "Your continued use of Apsara Talent after the effective date of the updated policy constitutes your acceptance of the changes.",
    },

    s11: {
      title: "Contact Us",
      intro:
        "If you have questions, concerns, or requests regarding this Privacy Policy or your personal data, please reach out:",
      address: "Phnom Penh, Cambodia",
    },
  },

  km: {
    back: "ត្រឡប់",
    pageTitle: "គោលការណ៍ភាពឯកជន",
    lastUpdated: "ធ្វើបច្ចុប្បន្នភាពចុងក្រោយ: ២៤ មីនា ២០២៦",
    tocHeading: "មាតិកា",
    intro:
      "នៅ Apsara Talent យើងប្តេជ្ញាចិត្តក្នុងការការពារព័ត៌មានផ្ទាល់ខ្លួនរបស់អ្នក។ គោលការណ៍ភាពឯកជននេះពន្យល់ពីទិន្នន័យដែលយើងប្រមូល មូលហេតុដែលយើងប្រមូល និងរបៀបដែលយើងប្រើប្រាស់ និងការពារវានៅពេលអ្នកប្រើប្រាស់វេទិកាផ្គូផ្គងទេព្យោសម្បទារបស់យើង។",
    introCompany: "Apsara Talent",

    toc: [
      { id: "information-we-collect", label: "ព័ត៌មានដែលយើងប្រមូល" },
      {
        id: "how-we-use",
        label: "របៀបដែលយើងប្រើប្រាស់ព័ត៌មានរបស់អ្នក",
      },
      {
        id: "how-we-share",
        label: "របៀបដែលយើងចែករំលែកព័ត៌មានរបស់អ្នក",
      },
      { id: "third-party", label: "សេវាកម្មភាគីទីបី" },
      { id: "data-retention", label: "ការរក្សាទុកទិន្នន័យ" },
      { id: "security", label: "សុវត្ថិភាព" },
      { id: "your-rights", label: "សិទ្ធិរបស់អ្នក" },
      { id: "cookies", label: "ខូគី និងការផ្ទុកក្នុងស្រុក" },
      { id: "children", label: "ភាពឯកជនរបស់កុមារ" },
      { id: "changes", label: "ការផ្លាស់ប្តូរគោលការណ៍នេះ" },
      { id: "contact", label: "ទំនាក់ទំនងពួកយើង" },
    ],

    s1: {
      title: "ព័ត៌មានដែលយើងប្រមូល",
      intro:
        "យើងប្រមូលព័ត៌មានដែលអ្នកផ្តល់ដោយផ្ទាល់ ព័ត៌មានដែលកើតឡើងពីការប្រើប្រាស់វេទិការបស់អ្នក និងព័ត៌មានពីសេវាកម្មភាគីទីបីដែលអ្នកភ្ជាប់។",
      g1Title: "គណនី និងអត្តសញ្ញាណ",
      g1: [
        "ឈ្មោះពេញ ឈ្មោះអ្នកប្រើ អ៊ីមែល និងលេខទូរស័ព្ទ",
        "ថ្ងៃខែឆ្នាំកំណើត និងភេទ (សម្រាប់និយោជិត)",
        "រូបភាពប្រវត្តិរូប / avatar ហើយសម្រាប់ក្រុមហ៊ុន រូបភាពគ្របដណ្តប់",
        "ពាក្យសម្ងាត់ (រក្សាទុកជា hash សុវត្ថិភាព — យើងមិនរក្សាទុកជាអក្សរធម្មតាឡើយ)",
        "អត្តសញ្ញាណ Social Login ពី Google, Facebook, LinkedIn ឬ GitHub នៅពេលអ្នកជ្រើសរើសវិធីចូលទាំងនោះ",
      ],
      g2Title: "ព័ត៌មានវិជ្ជាជីវៈ (និយោជិត)",
      g2: [
        "ức,ចំណងជើងការងារ ឆ្នាំបទពិសោធ ប្រភេទភាពទំនេរ និងវិស័យអាជីព",
        "ជំនាញ ប្រវត្តិការងារ និងការសិក្សា",
        "ឯកសារ Resume និង Cover Letter ដែលអ្នកផ្ទុកឡើង",
        "តំណភ្ជាប់ Social Profile (LinkedIn, GitHub, Website ។ល។)",
        "ទីតាំង (ខេត្ត/ក្រុង នៅកម្ពុជា)",
      ],
      g3Title: "ព័ត៌មានក្រុមហ៊ុន",
      g3: [
        "ឈ្មោះក្រុមហ៊ុន ឧស្សាហកម្ម ទំហំ ឆ្នាំបង្កើត និងការពិពណ៌នា",
        "មុខតំណែងការងារបើចំហ ពេលវេលាសំភាស និងតម្លៃ/អត្ថប្រយោជន៍ក្រុមហ៊ុន",
        "ទីតាំងក្រុមហ៊ុន និងព័ត៌មានទំនាក់ទំនង",
        "រូបភាពវិចិត្រសាលក្រុមហ៊ុន",
      ],
      g4Title: "ទិន្នន័យការប្រើប្រាស់ និងបច្ចេកទេស",
      g4: [
        "ទំព័រដែលបានចូលមើល មុខងារដែលប្រើ និងអន្តរកម្មក្នុងវេទិកា",
        "សារជជែកដែលផ្លាស់ប្តូររវាងអ្នកប្រើប្រាស់ក្នុងវេទិកា",
        "ការចូលចិត្ត និងសកម្មភាពផ្គូផ្គង (រក្សា ចូលចិត្ត ប្រៀប)",
        "Token ឧបករណ៍សម្រាប់ការជូនដំណឹង Push",
        "ពេលចូលចុងក្រោយ វិធីចូល និងអាសយដ្ឋាន IP",
        "ប្រភេទ Browser ប្រព័ន្ធប្រតិបត្តិការ និងកម្មវិធីកំណត់អត្តសញ្ញាណឧបករណ៍",
      ],
    },

    s2: {
      title: "របៀបដែលយើងប្រើប្រាស់ព័ត៌មានរបស់អ្នក",
      bullets: [
        "ដើម្បីបង្កើត ផ្ទៀងផ្ទាត់ និងថែរក្សាគណនីរបស់អ្នក",
        "ដើម្បីដំណើរការក្បួនអាល់ហ្គោរីតម​ផ្គូផ្គងទេព្យោសម្បទា ដែលបង្ហាញនិយោជិតដែលពាក់ព័ន្ធដល់ក្រុមហ៊ុន និងផ្ទុយ",
        "ដើម្បីបើកការផ្ញើសារជាក់ស្តែងរវាងអ្នកប្រើប្រាស់ដែលផ្គូផ្គងគ្នា",
        "ដើម្បីផ្ញើការជូនដំណឹង Push អំពីការផ្គូផ្គងថ្មី សារ និងការអាប់ដេតវេទិកា",
        "ដើម្បីបង្កើតព្រាង Resume ដោយ AI តាមរយៈមុខងារ Resume Builder",
        "ដើម្បីធ្វើបុគ្គលិកលក្ខណ Feed និងលទ្ធផលស្វែងរករបស់អ្នកតាមប្រវត្តិរូប និងសកម្មភាព",
        "ដើម្បីរកឃើញការក្លែងបន្លំ អនុវត្ត Terms of Service និងរក្សាសុវត្ថិភាពវេទិកា",
        "ដើម្បីផ្ញើអ៊ីមែលប្រតិបត្តិការ ដូចជា ការផ្ទៀងផ្ទាត់អ៊ីមែល ការកំណត់ពាក្យសម្ងាត់ឡើងវិញ និងការជូនដំណឹងអំពីសកម្មភាពគណនី",
        "ដើម្បីធ្វើឱ្យប្រសើរឡើង និងបង្កើតមុខងារថ្មីតាមរយៈការវិភាគដែលប្រមូលផ្តុំ និងធ្វើអ្វីអនាមិក",
      ],
      note: "",
      notePrefix: "យើង",
      noteStrong: "មិន",
      noteSuffix:
        "លក់ទិន្នន័យផ្ទាល់ខ្លួនរបស់អ្នកទៅភាគីទីបី ឬប្រើប្រាស់វាសម្រាប់គោលបំណងផ្សាយពាណិជ្ជកម្មដែលមិនពាក់ព័ន្ធឡើយ។",
    },

    s3: {
      title: "របៀបដែលយើងចែករំលែកព័ត៌មានរបស់អ្នក",
      intro:
        "យើងមិនលក់ ឬជួលទិន្នន័យផ្ទាល់ខ្លួនរបស់អ្នកឡើយ។ យើងចែករំលែកព័ត៌មានក្នុងករណីដែលមានកំណត់ខាងក្រោមប៉ុណ្ណោះ:",
      bullets: [
        {
          label: "ជាមួយអ្នកប្រើប្រាស់ផ្សេង:",
          text: "ប្រវត្តិរូបសាធារណៈរបស់អ្នក (ឈ្មោះ ការងារ ជំនាញ ទីតាំង ភាពទំនេរ ការពិពណ៌នា) អាចមើលឃើញដោយប្រភេទអ្នកប្រើប្រាស់ម្ខាងទៀត — និយោជិតអាចត្រូវបានក្រុមហ៊ុនមើលឃើញ ហើយក្រុមហ៊ុនអាចត្រូវបានគេមើលឃើញដោយនិយោជិត — ដើម្បីជួយឱ្យការផ្គូផ្គង និងការជ្រើសរើសសម្ភារៈ",
        },
        {
          label: "ជាមួយអ្នកផ្តល់សេវា:",
          text: "យើងប្រើអ្នកផ្តល់ហេដ្ឋារចនាសម្ព័ន្ធទំុកទុក (ហ៊ីបឌ័រ ទិន្នន័យ ការផ្ញើអ៊ីមែល) ដែលដំណើរការទិន្នន័យក្នុងនាមមយ្យួើងក្រោមកិច្ចព្រមព្រៀងដំណើរការទិន្នន័យយ៉ាងតឹងរ៉ឹង",
        },
        {
          label: "ជាមួយអ្នកផ្តល់ Social Login:",
          text: "នៅពេលអ្នកផ្ទៀងផ្ទាត់តាម Google, Facebook, LinkedIn ឬ GitHub សេវាទាំងនោះទទួលព័ត៌មានតាមគោលការណ៍ភាពឯកជនរបស់ពួកគេ",
        },
        {
          label: "ដើម្បីអនុលោមច្បាប់:",
          text: "យើងអាចបង្ហាញទិន្នន័យនៅពេលតម្រូវដោយច្បាប់កម្ពុជា បញ្ជាតុលាការ ឬដើម្បីការពារសិទ្ធិ និងសុវត្ថិភាពរបស់អ្នកប្រើប្រាស់",
        },
        {
          label: "នៅពេលផ្ទេរអាជីវកម្ម:",
          text: "ក្នុងករណីរួមបញ្ចូល придбання ឬការលក់ទ្រព្យ ទិន្នន័យរបស់អ្នកអាចត្រូវបានផ្ទេរទៅអង្គភាពស្នងតំណែង",
        },
      ],
    },

    s4: {
      title: "សេវាកម្មភាគីទីបី",
      intro:
        "Apsara Talent រួមបញ្ចូលសេវាកម្មភាគីទីបីខាងក្រោម។ នីមួយៗមានគោលការណ៍ភាពឯកជនផ្ទាល់ខ្លួនដែលគ្រប់គ្រងការប្រើប្រាស់ទិន្នន័យរបស់អ្នក:",
      bullets: [
        {
          label: "Google Firebase:",
          text: "ប្រើសម្រាប់ការជូនដំណឹង Push (Firebase Cloud Messaging)។ Token ឧបករណ៍របស់អ្នកត្រូវបានរក្សាទុកយ៉ាងសុវត្ថិភាព ហើយប្រើតែសម្រាប់ការជូនដំណឹងប៉ុណ្ណោះ",
        },
        {
          label: "Google OAuth / Google Sign-In:",
          text: "វិធីផ្ទៀងផ្ទាត់ជាជម្រើស។ យើងទទួលឈ្មោះ អ៊ីមែល និងរូបភាពប្រវត្តិរូបពី Google ប្រសិនបើអ្នកជ្រើសរើសជម្រើសនេះ",
        },
        {
          label: "Facebook Login:",
          text: "វិធីផ្ទៀងផ្ទាត់ជាជម្រើស ដែលអនុវត្តដោយ Meta's Data Policy",
        },
        {
          label: "LinkedIn OAuth:",
          text: "ការផ្ទៀងផ្ទាត់ជាជម្រើសសម្រាប់ការផ្ទៀងផ្ទាត់អត្តសញ្ញាណវិជ្ជាជីវៈ",
        },
        {
          label: "GitHub OAuth:",
          text: "ការផ្ទៀងផ្ទាត់ជាជម្រើសសម្រាប់អ្នកជំនាញបច្ចេកទេស",
        },
        {
          label: "ហេដ្ឋារចនាសម្ព័ន្ធ Cloud (Railway):",
          text: "API និងមូលដ្ឋានទិន្នន័យរបស់យើងត្រូវបានបង្ហោះនៅ Railway។ ទិន្នន័យត្រូវបានដំណើរការនៅក្នុងមជ្ឈមណ្ឌលទិន្នន័យដែលមានស្ដង់ដារ",
        },
      ],
    },

    s5: {
      title: "ការរក្សាទុកទិន្នន័យ",
      intro:
        "យើងរក្សាទិន្នន័យផ្ទាល់ខ្លួនរបស់អ្នករហូតដល់គណនីរបស់អ្នកនៅតែសកម្ម ឬតាមដែលត្រូវការដើម្បីផ្តល់សេវាកម្មដល់អ្នក។",
      bullets: [
        "ទិន្នន័យគណនីត្រូវបានរក្សាទុកตลอดអាយុជីវិតគណនីរបស់អ្នក",
        "សារជជែកត្រូវបានរក្សាទុកដើម្បីផ្តល់ប្រវត្តិការផ្ញើសារជាប់លាប់។ អ្នកអាចលុបការសន្ទនានីមួយៗបាន",
        "បន្ទាប់ពីការលុបគណនី យើងរក្សាទិន្នន័យខ្លះរហូតដល់ ៣០ ថ្ងៃ មុនការលុបជាអចិន្ត្រៃយ៍ ដើម្បីអនុញ្ញាតឱ្យស្ដារគណនី លើកលែងតែការរក្សាទុករយៈពេលវែងជាងនេះត្រូវបានតម្រូវដោយច្បាប់",
        "ទិន្នន័យការវិភាគដែលធ្វើអ្វីអនាមិក និងប្រមូលផ្តុំអាចត្រូវបានរក្សាទុកជារៀងរហូត ព្រោះវាមិនអាចភ្ជាប់ទៅបុគ្គលណាម្នាក់បានទេ",
      ],
    },

    s6: {
      title: "សុវត្ថិភាព",
      intro:
        "យើងអនុវត្តវិធានការសុវត្ថិភាពស្ដង់ដារឧស្សាហកម្មដើម្បីការពារទិន្នន័យរបស់អ្នក:",
      bullets: [
        "ទិន្នន័យទាំងអស់ត្រូវបានបញ្ជូនតាមការអ៊ិនគ្រីប HTTPS/TLS",
        "ពាក្យសម្ងាត់ត្រូវបាន hash ដោយប្រើក្បួន one-way ខ្លាំង ហើយមិនរក្សាទុកជាអក្សរធម្មតាឡើយ",
        "ការផ្ទៀងផ្ទាត់ Two-Factor (2FA) ជាជម្រើស ដើម្បីបន្ថែមស្រទាប់ការការពារគណនីបន្ថែម",
        "ការចូលប្រើទិន្នន័យផ្ទាល់ខ្លួនត្រូវបានកំណត់ចំពោះបុគ្គលិកដែលមានការអនុញ្ញាតប៉ុណ្ណោះ",
        "យើងធ្វើការពិនិត្យសុវត្ថិភាពឱ្យបានទៀងទាត់នៃហេដ្ឋារចនាសម្ព័ន្ធរបស់យើង",
      ],
      note: "ខណៈដែលយើងប្រុងប្រយ័ត្នគ្រប់ការ មិនមានវិធីណាមួយនៃការបញ្ជូនតាមអ៊ីនធឺណិតដែល ១០០% សុវត្ថិភាពទេ។ យើងលើកទឹកចិត្តឱ្យអ្នកប្រើពាក្យសម្ងាត់ខ្លាំង ពិសេស និងបើក 2FA។",
    },

    s7: {
      title: "សិទ្ធិរបស់អ្នក",
      intro: "អ្នកមានសិទ្ធិខាងក្រោមទាក់ទងទិន្នន័យផ្ទាល់ខ្លួនរបស់អ្នក:",
      bullets: [
        {
          label: "ការចូលប្រើ:",
          text: "ស្នើសុំច្បាប់ចម្លងនៃទិន្នន័យផ្ទាល់ខ្លួនដែលយើងកាន់អំពីអ្នក",
        },
        {
          label: "ការកែតម្រូវ:",
          text: "ធ្វើបច្ចុប្បន្នភាព ឬកែព័ត៌មានមិនត្រឹមត្រូវតាមការកំណត់ប្រវត្តិរូបរបស់អ្នកនៅពេលណាក៏បាន",
        },
        {
          label: "ការលុប:",
          text: "ស្នើសុំការលុបគណនី និងទិន្នន័យផ្ទាល់ខ្លួនរបស់អ្នក",
        },
        {
          label: "ការផ្ទេរ:",
          text: "ស្នើសុំការនាំចេញទិន្នន័យរបស់អ្នកក្នុងទម្រង់ដែលអាចអានដោយម៉ាស៊ីន",
        },
        {
          label: "ការជំទាស់:",
          text: "ជំទាស់ការដំណើរការទិន្នន័យរបស់អ្នកសម្រាប់គោលបំណងជាក់លាក់",
        },
        {
          label: "ដក​ការ​យល់ព្រម:",
          text: "ដក​ការ​យល់ព្រម​សម្រាប់​ការ​ដំណើរ​ការ​ទិន្នន័យ​ជា​ជម្រើស​នៅ​ពេល​ណា​ក​ដោយ​មិន​ប៉ះ​ពាល់​ការ​ដំណើរ​ការ​ពី​មុន",
        },
      ],
      note: "ដើម្បីប្រើសិទ្ធិទាំងនេះ សូមទាក់ទងពួកយើងនៅ",
      email: "privacy@apsaratalent.com",
      noteSuffix: "។ យើងនឹងឆ្លើយតបក្នុងរយៈពេល ៣០ ថ្ងៃ។",
    },

    s8: {
      title: "ខូគី និងការផ្ទុកក្នុងស្រុក",
      intro: "យើងប្រើខូគីកម្មវិធីរុករក និងការផ្ទុកក្នុងស្រុកដើម្បី:",
      bullets: [
        "រក្សាការចូលប្រើ Session របស់អ្នកដោយសុវត្ថិភាព",
        "ចងចាំចំណូលចិត្ត Theme (ភ្លឺ / ងងឹត / ប្រព័ន្ធ) របស់អ្នក",
        "ចងចាំចំណូលចិត្តភាសា (ភាសាអង់គ្លេស / ភាសាខ្មែរ) របស់អ្នក",
        "រក្សាទុកទិន្នន័យ Cache ក្នុងស្រុក ដើម្បីធ្វើឱ្យប្រសើរ Performance ការផ្ទុកទំព័រ",
      ],
      note: "យើងមិនប្រើខូគីផ្សាយពាណិជ្ជកម្មភាគីទីបីឡើយ។ អ្នកអាចលុបខូគី និងការផ្ទុកក្នុងស្រុកតាមការកំណត់ Browser របស់អ្នកនៅពេលណាក៏បាន ទោះជាក្តី វានឹងធ្វើឱ្យអ្នកចេញពីគណនី។",
    },

    s9: {
      title: "ភាពឯកជនរបស់កុមារ",
      text: "Apsara Talent ត្រូវបានរចនាសម្រាប់អ្នកប្រើប្រាស់ដែលមានអាយុ ១៨ ឆ្នាំ ឬលើសពីនេះ។ យើងមិនប្រមូលព័ត៌មានផ្ទាល់ខ្លួនពីបុគ្គលដែលមានអាយុក្រោម ១៨ ឆ្នាំដោយចេតនាឡើយ។ ប្រសិនបើយើងដឹងថាអ្នកប្រើប្រាស់មានអាយុក្រោម ១៨ ឆ្នាំ យើងនឹងលុបគណនី និងទិន្នន័យដែលពាក់ព័ន្ធរបស់ពួកគេឱ្យបានឆាប់រហ័ស។ ប្រសិនបើអ្នកជឿថាកុមារម្នាក់បានចុះឈ្មោះ សូមទាក់ទងពួកយើងភ្លាម។",
    },

    s10: {
      title: "ការផ្លាស់ប្តូរគោលការណ៍នេះ",
      intro:
        "យើងអាចធ្វើបច្ចុប្បន្នភាពគោលការណ៍ភាពឯកជននេះពីពេលទៅពេល ដើម្បីឆ្លុះបញ្ចាំងការផ្លាស់ប្តូរនៅក្នុងការអនុវត្ត បច្ចេកវិទ្យា តម្រូវការច្បាប់ ឬកត្តាផ្សេងៗ។ នៅពេលយើងធ្វើការផ្លាស់ប្តូរសំខាន់ យើងនឹង:",
      bullets: [
        'ធ្វើបច្ចុប្បន្នភាពកាលបរិច្ឆេទ "ធ្វើបច្ចុប្បន្នភាពចុងក្រោយ" នៅផ្នែកខាងលើទំព័រនេះ',
        "ផ្ញើការជូនដំណឹងដល់អ្នកប្រើប្រាស់ដែលចុះឈ្មោះតាមអ៊ីមែល ឬការជូនដំណឹងក្នុងកម្មវិធី",
      ],
      note: "ការប្រើប្រាស់ Apsara Talent ជានិច្ចរបស់អ្នកក្រោយពេលមានប្រសិទ្ធភាពនៃគោលការណ៍ដែលបានធ្វើបច្ចុប្បន្នភាព ស្មើនឹងការទទួលស្គាល់ការផ្លាស់ប្តូររបស់អ្នក។",
    },

    s11: {
      title: "ទំនាក់ទំនងពួកយើង",
      intro:
        "ប្រសិនបើអ្នកមានសំណួរ ការព្រួយបារម្ភ ឬការស្នើសុំទាក់ទងគោលការណ៍ភាពឯកជននេះ ឬទិន្នន័យផ្ទាល់ខ្លួនរបស់អ្នក សូមទំនាក់ទំនង:",
      address: "ភ្នំពេញ, កម្ពុជា",
    },
  },
};

/* -------------------------- Main Component -------------------------- */
export function PrivacyContent() {
  /* ------------------------------ Utils ----------------------------- */
  const { language, setLanguage } = useLanguageStore();
  const c = content[language];

  /* --------------------------- Render UI ---------------------------- */
  return (
    <div className="min-h-screen bg-background animate-page-in">
      {/* Top Navigation Section */}
      <header className="sticky top-0 z-10 border-b border-border/60 bg-background/95 backdrop-blur-sm">
        <div className="max-w-5xl mx-auto flex items-center gap-4 px-4 py-3 sm:px-6">
          <Link
            href="/setting"
            className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <LucideArrowLeft className="size-4" />
            {c.back}
          </Link>
          <span className="text-border">|</span>
          <span className="text-sm font-semibold truncate">{c.pageTitle}</span>

          {/* Language Toggle Section */}
          <div className="ml-auto flex items-center gap-1 rounded-lg border border-border bg-muted/40 p-0.5">
            <button
              onClick={() => setLanguage("en")}
              className={`px-2.5 py-1 rounded-md text-xs font-medium transition-colors ${
                language === "en"
                  ? "bg-background text-foreground shadow-sm"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              EN
            </button>
            <button
              onClick={() => setLanguage("km")}
              className={`px-2.5 py-1 rounded-md text-xs font-medium transition-colors ${
                language === "km"
                  ? "bg-background text-foreground shadow-sm"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              ខ្មែរ
            </button>
          </div>
        </div>
      </header>

      <div className="max-w-5xl mx-auto px-4 py-10 sm:px-6 lg:flex lg:gap-12">
        {/* Sticky TOC Sidebar Section (Desktop) */}
        <aside className="hidden lg:block w-56 shrink-0">
          <div className="sticky top-20 flex flex-col gap-1">
            <TypographySmall className="text-xs font-semibold uppercase tracking-widest text-muted-foreground mb-2">
              {c.tocHeading}
            </TypographySmall>
            {c.toc.map((item) => (
              <a
                key={item.id}
                href={`#${item.id}`}
                className="text-xs text-muted-foreground hover:text-primary transition-colors py-1 border-l-2 border-transparent hover:border-primary/50 pl-3"
              >
                {item.label}
              </a>
            ))}
          </div>
        </aside>

        {/* Main Content Section */}
        <main className="flex-1 flex flex-col gap-10 min-w-0">
          {/* Banner Section */}
          <div className="w-full flex items-center justify-between gap-6 lg:gap-10 rounded-2xl bg-gradient-to-br from-primary/[0.06] via-transparent to-muted/30 border border-border/50 px-6 py-8 sm:px-8">
            {/* Content Section */}
            <div className="flex flex-col items-start gap-3">
              <div className="flex items-center gap-2 text-xs text-muted-foreground">
                <LucideCalendar className="size-3.5" />
                <span>{c.lastUpdated}</span>
              </div>
              <TypographyH1 className="text-3xl font-bold tracking-tight">
                {c.pageTitle}
              </TypographyH1>
              <TypographyP className="text-muted-foreground text-sm leading-relaxed max-w-2xl">
                {language === "en" ? (
                  <>
                    At{" "}
                    <strong className="text-foreground">
                      {c.introCompany}
                    </strong>
                    {", "}
                    {c.intro.replace("At Apsara Talent, ", "")}
                  </>
                ) : (
                  <>
                    នៅ{" "}
                    <strong className="text-foreground">
                      {c.introCompany}
                    </strong>{" "}
                    {c.intro.replace("នៅ Apsara Talent ", "")}
                  </>
                )}
              </TypographyP>
            </div>

            {/* Editorial Illustration Section */}
            <EditorialIllustration
              variant="trust"
              className="hidden h-40 w-56 sm:block"
            />
          </div>

          {/* 1. Information We Collect Section */}
          <Section
            id="information-we-collect"
            icon={<LucideDatabase />}
            title={c.s1.title}
          >
            <TypographyP>{c.s1.intro}</TypographyP>
            <div className="flex flex-col gap-2">
              <TypographySmall className="font-medium text-foreground">
                {c.s1.g1Title}
              </TypographySmall>
              <ul className="flex flex-col gap-1.5 ml-1">
                {c.s1.g1.map((t, i) => (
                  <Bullet key={i}>{t}</Bullet>
                ))}
              </ul>
            </div>
            <div className="flex flex-col gap-2">
              <TypographySmall className="font-medium text-foreground">
                {c.s1.g2Title}
              </TypographySmall>
              <ul className="flex flex-col gap-1.5 ml-1">
                {c.s1.g2.map((t, i) => (
                  <Bullet key={i}>{t}</Bullet>
                ))}
              </ul>
            </div>
            <div className="flex flex-col gap-2">
              <TypographySmall className="font-medium text-foreground">
                {c.s1.g3Title}
              </TypographySmall>
              <ul className="flex flex-col gap-1.5 ml-1">
                {c.s1.g3.map((t, i) => (
                  <Bullet key={i}>{t}</Bullet>
                ))}
              </ul>
            </div>
            <div className="flex flex-col gap-2">
              <TypographySmall className="font-medium text-foreground">
                {c.s1.g4Title}
              </TypographySmall>
              <ul className="flex flex-col gap-1.5 ml-1">
                {c.s1.g4.map((t, i) => (
                  <Bullet key={i}>{t}</Bullet>
                ))}
              </ul>
            </div>
          </Section>

          {/* 2. How We Use Section */}
          <Section
            id="how-we-use"
            icon={<LucideUserCheck />}
            title={c.s2.title}
          >
            <ul className="flex flex-col gap-1.5 ml-1">
              {c.s2.bullets.map((t, i) => (
                <Bullet key={i}>{t}</Bullet>
              ))}
            </ul>
            <TypographyP>
              {c.s2.notePrefix}{" "}
              <strong className="text-foreground">{c.s2.noteStrong}</strong>{" "}
              {c.s2.noteSuffix}
            </TypographyP>
          </Section>

          {/* 3. How We Share Section */}
          <Section id="how-we-share" icon={<LucideShare2 />} title={c.s3.title}>
            <TypographyP>{c.s3.intro}</TypographyP>
            <ul className="flex flex-col gap-1.5 ml-1">
              {c.s3.bullets.map((b, i) => (
                <Bullet key={i}>
                  <strong className="text-foreground">{b.label}</strong>{" "}
                  {b.text}
                </Bullet>
              ))}
            </ul>
          </Section>

          {/* 4. Third-Party Services Section */}
          <Section id="third-party" icon={<LucideServer />} title={c.s4.title}>
            <TypographyP>{c.s4.intro}</TypographyP>
            <ul className="flex flex-col gap-1.5 ml-1">
              {c.s4.bullets.map((b, i) => (
                <Bullet key={i}>
                  <strong className="text-foreground">{b.label}</strong>{" "}
                  {b.text}
                </Bullet>
              ))}
            </ul>
          </Section>

          {/* 5. Data Retention Section */}
          <Section
            id="data-retention"
            icon={<LucideDatabase />}
            title={c.s5.title}
          >
            <TypographyP>{c.s5.intro}</TypographyP>
            <ul className="flex flex-col gap-1.5 ml-1">
              {c.s5.bullets.map((t, i) => (
                <Bullet key={i}>{t}</Bullet>
              ))}
            </ul>
          </Section>

          {/* 6. Security Section */}
          <Section id="security" icon={<LucideLock />} title={c.s6.title}>
            <TypographyP>{c.s6.intro}</TypographyP>
            <ul className="flex flex-col gap-1.5 ml-1">
              {c.s6.bullets.map((t, i) => (
                <Bullet key={i}>{t}</Bullet>
              ))}
            </ul>
            <TypographyP>{c.s6.note}</TypographyP>
          </Section>

          {/* 7. Your Rights Section */}
          <Section
            id="your-rights"
            icon={<LucideShieldCheck />}
            title={c.s7.title}
          >
            <TypographyP>{c.s7.intro}</TypographyP>
            <ul className="flex flex-col gap-1.5 ml-1">
              {c.s7.bullets.map((b, i) => (
                <Bullet key={i}>
                  <strong className="text-foreground">{b.label}</strong>{" "}
                  {b.text}
                </Bullet>
              ))}
            </ul>
            <TypographyP>
              {c.s7.note}{" "}
              <a
                href={`mailto:${c.s7.email}`}
                className="text-primary hover:underline"
              >
                {c.s7.email}
              </a>
              {c.s7.noteSuffix}
            </TypographyP>
          </Section>

          {/* 8. Cookies Section */}
          <Section id="cookies" icon={<LucideDatabase />} title={c.s8.title}>
            <TypographyP>{c.s8.intro}</TypographyP>
            <ul className="flex flex-col gap-1.5 ml-1">
              {c.s8.bullets.map((t, i) => (
                <Bullet key={i}>{t}</Bullet>
              ))}
            </ul>
            <TypographyP>{c.s8.note}</TypographyP>
          </Section>

          {/* 9. Children Section */}
          <Section id="children" icon={<LucideUser />} title={c.s9.title}>
            <TypographyP>{c.s9.text}</TypographyP>
          </Section>

          {/* 10. Changes Section */}
          <Section id="changes" icon={<LucideRefreshCw />} title={c.s10.title}>
            <TypographyP>{c.s10.intro}</TypographyP>
            <ul className="flex flex-col gap-1.5 ml-1">
              {c.s10.bullets.map((t, i) => (
                <Bullet key={i}>{t}</Bullet>
              ))}
            </ul>
            <TypographyP>{c.s10.note}</TypographyP>
          </Section>

          {/* 11. Contact Section */}
          <Section id="contact" icon={<LucideMail />} title={c.s11.title}>
            <TypographyP>{c.s11.intro}</TypographyP>
            <div className="rounded-xl border border-border bg-muted/30 p-4 flex flex-col gap-1.5">
              <TypographySmall className="font-semibold text-foreground">
                Apsara Talent
              </TypographySmall>
              <TypographyP>
                📧{" "}
                <a
                  href="mailto:privacy@apsaratalent.com"
                  className="text-primary hover:underline"
                >
                  privacy@apsaratalent.com
                </a>
              </TypographyP>
              <TypographyP>
                🌐{" "}
                <a
                  href="https://apsaratalent.com"
                  className="text-primary hover:underline"
                >
                  apsaratalent.com
                </a>
              </TypographyP>
              <TypographyP>📍 {c.s11.address}</TypographyP>
            </div>
          </Section>
        </main>
      </div>
    </div>
  );
}
